GET http://localhost:8080/users/2

###
POST http://localhost:8080/users
Content-Type: application/json

{
  "name": "Bernardo Jaco",
  "email": "bjaco@gmail.com"
}

###
GET http://localhost:8080/users?limit=2&skip=0
Accept: application/json

###
GET http://localhost:8080/clubs/1
Accept: application/json

###
GET http://localhost:8080/clubs?limit=10&skip=0
Accept: application/json

###
POST http://localhost:8080/club
Authorization: Bearer dc353bf9-7d3b-493a-847f-50c40fb4d34a
Content-Type: application/json

{
  "name": "Padel Jaco2"
}

###
POST http://localhost:8080/courts
Authorization: Bearer dc353bf9-7d3b-493a-847f-50c40fb4d34a
Content-Type: application/json

{
  "name": "Campo L",
  "cid": 2
}

###
GET http://localhost:8080/courts/1
Accept: application/json

###
GET http://localhost:8080/clubs/1/courts?limit=2&skip=0
Accept: application/json

###
POST http://localhost:8080/rental
Authorization: Bearer 6f1dab46-dc62-4f52-ac55-3afb43a41a19
Content-Type: application/json

{
  "cid": 1,
  "crid": 1,
  "date": "2021-06-03",
  "initDuration": 2,
  "endDuration": 10
}

###
GET http://localhost:8080/rentals/available?cid=1&crid=1&date=2025-04-30
Content-Type: application/json

###
GET http://localhost:8080/rentals/2
Accept: application/json

###
GET http://localhost:8080/rentals/user/1
Accept: application/json

###
GET http://localhost:8080/rentals?cid=1&crid=1&date=2021-06-01
Content-Type: application/json

###
GET http://localhost:8080/rentals/courts/1
Accept: application/json

###
DELETE http://localhost:8080/rentalsd/1
Accept: application/json

###
PUT http://localhost:8080/rentalsu/3?date=2025-05-01&initD=10&endD=11
Authorization: Bearer dc353bf9-7d3b-493a-847f-50c40fb4d34a
Content-Type: application/json

