
#create a new user -> create a new club -> create a new court -> create a new rental -> create another rental -> get the rental list

###
POST http://localhost:8081/users
Content-Type: application/json

{
    "name": "Miguel",
    "email": "afonso@gmail.com"
}

###
POST http://localhost:8081/club
Authorization: 0005d4c5-82c1-468c-bdef-e4db4e5700f3
Content-Type: application/json

{
"name": "Fly Padel 2"
}


###
POST http://localhost:8081/courts
Content-Type: application/json
Authorization: 0005d4c5-82c1-468c-bdef-e4db4e5700f3

{
  "name": "Padel Court 2",
  "cid" : 1
}

###
POST http://localhost:8081/rental
Authorization: Bearer 4007f4c6-08d2-4c39-af6a-1dbd5b4f2aff
Content-Type: application/json

{
  "cid": 1,
  "crid": 1,
  "date": "2021-06-01",
  "initDuration": "12",
  "endDuration": "16"
}


###
POST http://localhost:8081/rental
Authorization: 0005d4c5-82c1-468c-bdef-e4db4e5700f3
Content-Type: application/json

{
  "cid": 1,
  "crid": 1,
  "date": "2021-06-01",
  "initDuration": "12",
  "endDuration": "16"
}

###
GET http://localhost:8081/rentals
Content-Type: application/json

{
    "cid": 2,
    "crid": 2,
    "date": "2021-06-01",
    "initDuration": 0,
    "endDuration": 16
}


###

GET http://localhost:8081/rentals/available
Content-Type: application/json

{
"cid": 2,
"crid": 2,
"date": "2021-06-01",
  "initDuration": 12,
  "endDuration": 16
}


###

GET http://localhost:8081/rentals/user/2
Content-Type: application/json
