GET http://localhost:8082/users/1
###
GET http://localhost:8082/users/4
Accept: application/json
###
POST http://localhost:8082/users
Content-Type: application/json

{
  "name": "Pedro Pereira",
  "email": "pp@gmail.com"
}


###
GET http://localhost:8082/courts/1
Accept: application/json

###
GET http://localhost:8082/courts/2
Accept: application/json

###
POST http://localhost:8082/courts
Content-Type: application/json
Authorization: Bearer 42449fc7-0006-458d-b4dc-324d5583f634

{
  "name": "Padel Court 1",
  "id" : 1
}



