GET http://localhost:8082/users/1
###
GET http://localhost:8082/users/4
Accept: application/json
###
POST http://localhost:8082/users
Content-Type: application/json

{
  "name": "Pedro Pereira",
  "email": "pp@gmail.com"
}


###
GET http://localhost:8080/courts/1
Accept: application/json

###
GET http://localhost:8082/courts/3
Accept: application/json

###
POST http://localhost:8082/courts
Content-Type: application/json
Authorization: Bearer e8c7ee5d-9365-4754-8413-fe0961ce2cb0

{
  "name": "Padel Court 1",
  "cid" : 1
}

###
GET http://localhost:8082/clubs/2/courts
Accept: application/json



