

POST http://localhost:8080/users
Content-Type: application/json

{
  "name": "Luka Roca",
  "email": "lukastrocaaaaa@gmail.com",
  "password": "lukaroca1rfewfewvew23456"
}

###
POST http://localhost:8080/club
Authorization: 8d898818-81f5-4d2e-9320-ee305ebbcd89
Content-Type: application/json

{
  "name": "Bartolo 4"
}

###
POST http://localhost:8080/courts
Authorization: 8d898818-81f5-4d2e-9320-ee305ebbcd89
Content-Type: application/json


{
  "name": "Padel Court 4",
  "cid": 1
}

###
POST http://localhost:8080/rental
Authorization: Bearer 0cc14d4a-0b1a-4591-b43a-b958f1e3c8e0
Content-Type: application/json

{
  "cid": 1,
  "crid": 1,
  "date": "2021-06-01",
  "initDuration": "12",
  "endDuration": "16"
}

###
POST http://localhost:8080/rental
Authorization: Bearer 73cf5730-fec3-4202-9a1c-63708d534ab9
Content-Type: application/json

{
  "cid": 1,
  "crid": 1,
  "date": "2021-06-01",
  "initDuration": "12",
  "endDuration": "16"
}

###
GET http://localhost:8080/rentals?cid=1&crid=1&date=2021-06-01
Content-Type: application/json

###
GET http://localhost:8081/rentals/available?cid=1&crid=1&date=2021-06-01&initDuration=12&endDuration=16
Content-Type: application/json

###
GET http://localhost:8081/rentals/user/2
Content-Type: application/json

###
GET http://localhost:8080/users
content-type: application/json

###
GET http://localhost:8080/clubs?limit=2&skip=0
content-type: application/json

###
DELETE http://localhost:8080/clubd/1
content-type: application/json

###
GET http://localhost:8080/rental/date?date=2020-06-01
content-type: application/json

