GET http://localhost:8080/users/2

###
GET http://localhost:8080/clubs/1
Accept: application/json

###
GET http://localhost:8080/clubs
Accept: application/json

###
POST http://localhost:8080/club
Authorization: Bearer 990601b6-7240-4b0a-bf87-9e947bea0a88
Content-Type: application/json

{
  "name": "Padel N"
}

###
POST http://localhost:8080/users
Content-Type: application/json

{
    "name": "Bernardo Jaco",
    "email": "bjaco@gmail.com"
}

