package pt.isel.ls.utils

import kotlin.random.Random

/**
 * Generates a random string of characters.
 *
 * The string length is randomly chosen between 5 and 15 characters.
 * The characters in the string are selected from the English alphabet (both lowercase and uppercase).
 *
 * @return A randomly generated string.
 */
fun generateRandomString(): String {
    // Define the characters allowed in the random string
    val allowedChars = ('a'..'z') + ('A'..'Z')
    // Generate a list of random characters with a random length between 5 and 15
    return List(Random.nextInt(5, 16)) { allowedChars.random() }.joinToString("")
}

/**
 * Generates a random email address.
 *
 * The email address is generated by concatenating a random string before the '@' symbol
 * with another random string after the '@' symbol and appending '.com' at the end.
 *
 * @return A randomly generated email address.
 */
fun generateRandomEmail(): Email = Email("${generateRandomString()}@${generateRandomString()}.com")


/**
 * Generates a random strong password.
 *
 * The generated password meets the following criteria:
 * - At least 8 characters long.
 * - Contains at least one uppercase letter.
 * - Contains at least one lowercase letter.
 * - Contains at least one digit.
 * - Contains at least one special character from the set `!@#\$%^&*`.
 *
 * @param length The length of the password to generate. Must be at least 8 characters long. Defaults to 10 if not specified.
 * @return A randomly generated strong password as a [String].
 * @throws IllegalArgumentException if the specified length is less than 8.
 */

fun generateRandomPassword(length: Int = 10): Password {
    val uppercaseLetters = ('A'..'Z').toList()
    val lowercaseLetters = ('a'..'z').toList()
    val digits = ('0'..'9').toList()
    val specialCharacters = listOf('!', '@', '#', '$', '%', '^', '&', '*')

    require(length >= 8) { "Password length must be at least 8 characters." }

    val passwordChars = mutableListOf<Char>().apply {
        add(uppercaseLetters.random())
        add(lowercaseLetters.random())
        add(digits.random())
        add(specialCharacters.random())
    }

    val allChars = uppercaseLetters + lowercaseLetters + digits + specialCharacters

    repeat(length - 4) {
        passwordChars.add(allChars.random())
    }

    return Password(passwordChars.shuffled().joinToString(""))
}

